-- require('gitsigns').setup({
--   on_attach = function(bufnr)
--     local gs = package.loaded.gitsigns
--
--     vim.keymap.set('n', ']c', function()
--       if vim.wo.diff then
--         return ']c'
--       end
--       vim.schedule(gs.next_hunk)
--       return '<Ignore>'
--     end, { buffer = bufnr, expr = true })
--
--     vim.keymap.set('n', '[c', function()
--       if vim.wo.diff then
--         return '[c'
--       end
--       vim.schedule(gs.prev_hunk)
--       return '<Ignore>'
--     end, { buffer = bufnr, expr = true })
--   end,
-- })
