local add = MiniDeps.add

add('nvim-treesitter/nvim-treesitter-context')
---@diagnostic disable-next-line: missing-fields
require('nvim-treesitter.configs').setup({
  highlight = {
    enable = true,
  },
  indent = {
    enable = true,
  },
  ensure_installed = {
    'awk',
    'bash',
    'c',
    'c_sharp',
    'cmake',
    'comment',
    'cpp',
    'css',
    'css',
    'csv',
    'diff',
    'disassembly',
    'dockerfile',
    'editorconfig',
    'embedded_template',
    'elixir',
    'erlang',
    'fish',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'gleam',
    'go',
    'gomod',
    'gosum',
    'gotmpl',
    'gowork',
    'graphql',
    'haskell',
    'hcl',
    'html',
    'htmldjango',
    'http',
    'hurl',
    'ini',
    'java',
    'javascript',
    'jq',
    'jsdoc',
    'json',
    'json5',
    'jsonc',
    'jsonnet',
    'just',
    'lua',
    'luadoc',
    'make',
    'markdown',
    'markdown_inline',
    'nim',
    'nim_format_string',
    'nix',
    'ocaml',
    'ocaml_interface',
    'ocamllex',
    'passwd',
    'pem',
    'perl',
    'printf',
    'proto',
    'python',
    'query',
    'regex',
    'requirements',
    'rst',
    'ruby',
    'rust',
    'scss',
    'sql',
    'ssh_config',
    'starlark',
    'svelte',
    'swift',
    'terraform',
    'textproto',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'xml',
    'yaml',
    'zig',
  },
  textobjects = {
    select = {
      enable = true,

      -- Automatically jump forward to textobj, similar to targets.vim
      lookahead = true,

      keymaps = {
        -- You can use the capture groups defined in textobjects.scm
        ['af'] = '@function.outer',
        ['if'] = '@function.inner',
        ['ac'] = '@class.outer',
        ['ic'] = { query = '@class.inner', desc = 'Select inner part of a class region' },
      },

      selection_modes = {
        ['@parameter.outer'] = 'v',
        ['@function.outer'] = 'V',
        ['@class.outer'] = 'V',
        -- ['@class.outer'] = '<c-v>',
      },
    },
  },
})

add('nvim-treesitter/nvim-treesitter-textobjects')
